# Decision Tree Classifier

In [17]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
#Data Loading
df = pd.read_csv(r"D:\DATA_SCIENCE\DATA_SCIENCE\Clean_Dataset.csv")
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [5]:
#Data Info Gathering
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  str
 2   flight            300153 non-null  str
 3   source_city       300153 non-null  str
 4   departure_time    300153 non-null  str
 5   stops             300153 non-null  str
 6   arrival_time      300153 non-null  str
 7   destination_city  300153 non-null  str
 8   class             300153 non-null  str
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), str(8)
memory usage: 42.9 MB

In [6]:
df.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [7]:
df.shape

(300153, 12)

In [8]:
#Data Cleaning
df.isnull().sum()

Unnamed: 0          0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.drop(columns=['Unnamed: 0','flight'],inplace=True)

In [11]:
df.duplicated().sum()

np.int64(2213)

In [12]:
df=df.drop_duplicates()

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
# Create price category column
def price_category(price):
    if price <= 10000:
        return 'Budget'
    elif price <= 30000:
        return 'Mid'
    else:
        return 'Premium'

df['price_category'] = df['price'].apply(price_category)
print(df['price_category'].value_counts())

price_category
Budget     171815
Premium     87407
Mid         38718
Name: count, dtype: int64

In [15]:
# X and Y for Classifier
X_clf = df.drop(['price', 'price_category'], axis=1)
Y_clf = df['price_category']

In [18]:
# Encoding
le2 = LabelEncoder()
X_clf['airline'] = le2.fit_transform(X_clf['airline'])
X_clf['source_city'] = le2.fit_transform(X_clf['source_city'])
X_clf['departure_time'] = le2.fit_transform(X_clf['departure_time'])
X_clf['stops'] = le2.fit_transform(X_clf['stops'])
X_clf['arrival_time'] = le2.fit_transform(X_clf['arrival_time'])
X_clf['destination_city'] = le2.fit_transform(X_clf['destination_city'])
X_clf['class'] = le2.fit_transform(X_clf['class'])

In [19]:
# Split
X_train_c, X_test_c, Y_train_c, Y_test_c = train_test_split(X_clf, Y_clf, test_size=0.2, random_state=42)

print("Train size:", X_train_c.shape)
print("Test size:", X_test_c.shape)

Train size: (238352, 9)
Test size: (59588, 9)

In [20]:
# Model
clf_model = DecisionTreeClassifier(max_depth=15, min_samples_split=20, min_samples_leaf=10, random_state=42)
clf_model.fit(X_train_c, Y_train_c)
y_pred_clf = clf_model.predict(X_test_c)

In [21]:
# Evaluation
print("Train Score:", round(clf_model.score(X_train_c, Y_train_c), 2))
print("Test Score :", round(clf_model.score(X_test_c, Y_test_c), 2))
print("Accuracy   :", round(accuracy_score(Y_test_c, y_pred_clf), 2))
print()
print("Classification Report:")
print(classification_report(Y_test_c, y_pred_clf))
print()
print("Confusion Matrix:")
print(confusion_matrix(Y_test_c, y_pred_clf))

Train Score: 0.97
Test Score : 0.96
Accuracy   : 0.96

Classification Report:
              precision    recall  f1-score   support

      Budget       0.96      0.98      0.97     34486
         Mid       0.88      0.81      0.84      7703
     Premium       1.00      0.99      1.00     17399

    accuracy                           0.96     59588
   macro avg       0.94      0.93      0.94     59588
weighted avg       0.96      0.96      0.96     59588


Confusion Matrix:
[[33705   781     0]
 [ 1416  6249    38]
 [    2    97 17300]]