# Decision Tree Regressor

In [28]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score

In [13]:
#Data Loading
df = pd.read_csv(r"D:\DATA_SCIENCE\DATA_SCIENCE\Clean_Dataset.csv")
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [14]:
#Data Info Gathering
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  str
 2   flight            300153 non-null  str
 3   source_city       300153 non-null  str
 4   departure_time    300153 non-null  str
 5   stops             300153 non-null  str
 6   arrival_time      300153 non-null  str
 7   destination_city  300153 non-null  str
 8   class             300153 non-null  str
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), str(8)
memory usage: 42.9 MB

In [15]:
df.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [16]:
df.shape

(300153, 12)

In [17]:
#Data Cleaning
df.isnull().sum()

Unnamed: 0          0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.drop(columns=['Unnamed: 0','flight'],inplace=True)

In [20]:
df.duplicated().sum()

np.int64(2213)

In [21]:
df=df.drop_duplicates()

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
# Redo X and Y for Regressor
X_reg = df.drop(['price'], axis=1)  # keep class this time, whole column except price
Y_reg = df['price']                 # target / predicting price

In [24]:
# Encode all categorical columns
le = LabelEncoder()
X_reg['airline'] = le.fit_transform(X_reg['airline'])
X_reg['source_city'] = le.fit_transform(X_reg['source_city'])
X_reg['departure_time'] = le.fit_transform(X_reg['departure_time'])
X_reg['stops'] = le.fit_transform(X_reg['stops'])
X_reg['arrival_time'] = le.fit_transform(X_reg['arrival_time'])
X_reg['destination_city'] = le.fit_transform(X_reg['destination_city'])
X_reg['class'] = le.fit_transform(X_reg['class'])

In [25]:

# Train test split
X_train, X_test, Y_train, Y_test = train_test_split(X_reg, Y_reg, test_size=0.2, random_state=42)

In [26]:
# Model
reg_model = DecisionTreeRegressor(max_depth=15, min_samples_split=20, min_samples_leaf=10, random_state=42)
reg_model.fit(X_train, Y_train)
y_pred_reg = reg_model.predict(X_test)

In [29]:
print("Train Score:", round(reg_model.score(X_train, Y_train), 2))
print("Test Score :", round(reg_model.score(X_test, Y_test), 2))
print("R2 Score   :", round(r2_score(Y_test, y_pred_reg), 2))

Train Score: 0.98
Test Score : 0.98
R2 Score   : 0.98